# SPARC Framework Documentation Site
# Trigger build after GitHub Actions source configuration  
title: "SPARC Framework by ProductFoundry.ai"
description: "Structured Product Architecture Requirement Creation - A comprehensive development framework for building high-quality software through structured agent workflows and test-driven development."
url: "https://rsham004.github.io"
baseurl: "/claude-sparc-agent-config"

# Author
author:
  name: "ProductFoundry.ai Community"
  email: "community@productfoundry.ai"

# Theme (GitHub Pages compatible)
remote_theme: pages-themes/minimal@v0.2.0

# Plugins (GitHub Pages whitelist)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown
markdown: kramdown
highlighter: rouge

# Features for landing page
features:
  - title: "🎨 Color-Coded Agents"
    description: "Eight specialized agents following Claude Code best practices with unique color identification for streamlined workflow management."
  - title: "🧪 TDD-Guard Integration"
    description: "Enforced test-driven development with automatic violation tracking and Git issue management for quality assurance."
  - title: "🤖 Claude Code Optimized"
    description: "Purpose-built for Claude Code with proper memory management, project initialization, and natural language commands."
  - title: "🏗️ Community Built"
    description: "Developed by the ProductFoundry.ai community with shared values, open development, and collaborative innovation."